ruleset {

    description '''
        A Sample Groovy RuleSet containing all CodeNarc Rules, grouped by category.
        You can use this as a template for your own custom RuleSet.
        Just delete the rules that you don't want to include.
        '''

    // rulesets/basic.xml
    AssertWithinFinallyBlock()
    AssignmentInConditional()
    BigDecimalInstantiation()
    BitwiseOperatorInConditional()
    BooleanGetBoolean()
    BrokenNullCheck()
    BrokenOddnessCheck()
    ClassForName()
    ComparisonOfTwoConstants()
    ComparisonWithSelf()
    ConstantAssertExpression()
    ConstantIfExpression()
    ConstantTernaryExpression()
    DeadCode()
    DoubleNegative()
    DuplicateCaseStatement()
    DuplicateMapKey()
    DuplicateSetValue()
    EmptyCatchBlock()
    EmptyClass()
    EmptyElseBlock()
    EmptyFinallyBlock()
    EmptyForStatement()
    EmptyIfStatement()
    EmptyInstanceInitializer()
    EmptyStaticInitializer()
    EmptySwitchStatement()
    EmptySynchronizedStatement()
    EmptyTryBlock()
    EmptyWhileStatement()
    EqualsAndHashCode()
    EqualsOverloaded()
    ExplicitGarbageCollection()
    ForLoopShouldBeWhileLoop()
    HardCodedWindowsFileSeparator()
    HardCodedWindowsRootDirectory()
    IntegerGetInteger()
    MultipleUnaryOperators()
    ParameterAssignmentInFilterClosure()
    RandomDoubleCoercedToZero()
    RemoveAllOnSelf()
    ReturnFromFinallyBlock()
    ThrowExceptionFromFinallyBlock()

    // rulesets/braces.xml
    ElseBlockBraces()
    ForStatementBraces()
    IfStatementBraces()
    WhileStatementBraces()

    // rulesets/concurrency.xml
    BusyWait()
    DoubleCheckedLocking()
    InconsistentPropertyLocking()
    InconsistentPropertySynchronization()
    NestedSynchronization()
    NoScriptBindings()
    StaticCalendarField()
    StaticConnection()
    StaticDateFormatField()
    StaticMatcherField()
    StaticSimpleDateFormatField()
    SynchronizedMethod()
    SynchronizedOnBoxedPrimitive()
    SynchronizedOnGetClass()
    SynchronizedOnReentrantLock()
    SynchronizedOnString()
    SynchronizedOnThis()
    SynchronizedReadObjectMethod()
    SystemRunFinalizersOnExit()
    ThisReferenceEscapesConstructor()
    ThreadGroup()
    ThreadLocalNotStaticFinal()
    ThreadYield()
    UseOfNotifyMethod()
    VolatileArrayField()
    VolatileLongOrDoubleField()
    WaitOutsideOfWhileLoop()

    // rulesets/convention.xml
    ConfusingTernary()
    CouldBeElvis()
    HashtableIsObsolete()
    InvertedCondition()
    InvertedIfElse()
    LongLiteralWithLowerCaseL()
    NoDouble()
    NoFloat()
    NoJavaUtilDate()
    NoTabCharacter()
    PublicMethodsBeforeNonPublicMethods()
    StaticFieldsBeforeInstanceFields()
    StaticMethodsBeforeInstanceMethods()
    TernaryCouldBeElvis()
    TrailingComma()
    VectorIsObsolete()

    // rulesets/design.xml
    AbstractClassWithoutAbstractMethod()
    AssignmentToStaticFieldFromInstanceMethod()
    BooleanMethodReturnsNull()
    CloneableWithoutClone()
    CloseWithoutCloseable()
    CompareToWithoutComparable()
    ConstantsOnlyInterface()
    EmptyMethodInAbstractClass()
    FinalClassWithProtectedMember()
    LocaleSetDefault()
    OptionalCollectionReturnType()
    OptionalField()
    OptionalMethodParameter()
    PrivateFieldCouldBeFinal()
    PublicInstanceField()
    ReturnsNullInsteadOfEmptyArray()
    ReturnsNullInsteadOfEmptyCollection()
    SimpleDateFormatMissingLocale()
    StatelessSingleton()
    ToStringReturnsNull()

    // rulesets/exceptions.xml
    CatchArrayIndexOutOfBoundsException()
    CatchError()
    CatchIllegalMonitorStateException()
    CatchIndexOutOfBoundsException()
    CatchNullPointerException()
    CatchRuntimeException()
    CatchThrowable()
    ConfusingClassNamedException()
    ExceptionExtendsError()
    ExceptionExtendsThrowable()
    ExceptionNotThrown()
    MissingNewInThrowStatement()
    ReturnNullFromCatchBlock()
    SwallowThreadDeath()
    ThrowError()
    ThrowNullPointerException()
    ThrowRuntimeException()
    ThrowThrowable()
}
