{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.externalSecrets.secretStore.kind }}
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  {{- if eq .Values.externalSecrets.secretStore.kind "SecretStore" }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    "app.kubernetes.io/name": '{{ template "jenkins.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ template "jenkins.label" .}}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.controller.componentName }}"
spec:
  provider:
    aws:
      service: {{ .Values.externalSecrets.secretStore.aws.service }}
      region: {{ .Values.externalSecrets.secretStore.aws.region }}
{{- end }}